# Generated by Django 5.2.1 on 2025-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=200)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
